### ISSUE TITLE
Cannot update and install aria2 and exfat 

### ISSUE THREAD

**Issue by joychase** [Alter0ne/rtl8196e#1]
Cannot update and install aria2 and exfat, how to install and update software with this built?

**Comment by Alter0ne** [comment]
Hello,
aria2_1.18.7 is built without problems, aria2_1.35.0 is not tested now.
I added exfat support through either exfat-nofuse or rtl-fs modules. Please update the source and check the operability. There are compiled packages:
[https://yadi.sk/d/mpm3vpBcs7fk2g](aria2)
[https://yadi.sk/d/kiyHstRBFJNfsA](exfat)
